const ENV = process.env;

export const API_URL = ENV.EXPO_PUBLIC_API_KEY;
export const AUTH_DOMAIN = ENV.EXPO_PUBLIC_AUTH_DOMAIN;
export const PROJECT_ID = ENV.EXPO_PUBLIC_PROJECT_ID;
export const STORAGE_BUCKET = ENV.EXPO_PUBLIC_STORAGE_BUCKET;
export const MESSAGING_SENDER_ID = ENV.EXPO_PUBLIC_MESSAGING_SENDER_ID;
export const APP_ID = ENV.EXPO_PUBLIC_APP_ID;
export const MEASUREMENT_ID = ENV.EXPO_PUBLIC_MEASUREMENT_ID;
